### model
model_name_or_path: models/deepseek-coder-6.7b-base/new_sft_with_all_bug

### method
stage: dpo
do_train: true
finetuning_type: full
deepspeed: ds_z3_config.json

### dataset
dataset: self_contrast_correct_cot_QA, self_contrast_incorrect_cot_QA
template: deepseekcoder

cutoff_len: 8192
overwrite_cache: true
preprocessing_num_workers: 8

### output
output_dir: models/deepseek-coder-6.7b-base/self_contrast
overwrite_output_dir: true
logging_steps: 1
save_strategy: epoch

plot_loss: true
report_to: wandb
run_name: deepseek-coder-6.7b-self_contrast


### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 1
learning_rate: 1.0e-6
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
fp16: true
